#!/usr/bin/env python3

name = input("What is your name? ")
if name == "Mark":
   print("Coorect")
elif name == "Jo":
     print("you have a boring name? ")
else:
    print("coorect") 
quest = input("What is your quest? ")


color = input("What is your favorite color? ")

capital of acedia = input
print("You answered")
print("Your name is  {}".format(name))
print("Your quest is {}".format(quest))
print("Your color is {}".format(color))


