#!/usr/bin/python3

name = input("What is your name? ")
if name == "Mark":
   print("c.green +  Coorect" + c.reset)
else:
    print("coorect") 
quest = input("What is your quest? ")


color = input("What is your favorite color? ")

capital of acedia = input("What is the capital of Acidea? ")

asped volicity of a unlegged swallow = ("what is the asped volicity of a unlegged swallow? ")
if asped volicity of a unlegged swallow == ("European or African")
	print("I do not know that ahhh") 
else: 
	print(' c.red + Incorrect + c.reset')

print("You answered")
print("Your name is  {}".format(name))
print("Your quest is {}".format(quest))
print("Your color is {}".format(color))


