#!/usr/bin/env python3

import colors as c
from ultils import ask

text = '''Story Of War

It was during the battle of {Noun} when I was running through a {Noun1} when a {Noun2} went off right next to my platoon. 
Our {Job} yelled for us to {Verb} to the nearest {Place} we could find. 
When we got to the {Place} we {Verb ending with 'ED'} to start a fire. 
As we were starting the fire the enemy saw the {Noun3} from the fire and started {Verb ending with 'ING'} {Noun(Plural)} at us. 
We all quickly ducked behind the {Noun5} at the {Place} and returned fire. 
We quickly eliminated the enemy and were {Emotion} that we had won the battle.
'''

lines = text.splitlines()
title = lines[0]
text = "\n".join(lines[1:])

print(c.clear + c.base3 + title + c.reset)

words = {
    "Noun" : None,
    "Noun1": None,
    "Noun2" : None,
    "Noun3" : None,
    "Job" : None,
    "Verb" : None,
    "Place" : None,
    "Place" : None,
    "Verb ending with 'ED'" : None,
    "Verb ending with 'ING'" : None,
    "Noun(Plural)" : None,
    "Noun5" : None,
    "Place" : None,
    "Emotion" : None,
}

for key in words:
    words[key] = c.magenta + ask(key.rstrip('0123456789') + ': ') + c.reset

print(c.clear + c.base3 + title + c.reset)
print(text.format(**words))

