#!/usr/bin/env python3

import colors as c
import sys

print(c.clear + c.red + 'Multiplication Table' + c.reset)

if len(sys.argv) < 2:
    number = input(c.orange + 'PLease Enter a Number: ' + c.reset )
else:
    number = sys.argv[1] 

for count in range(12,0,-2):
    print(c.yellow, count, c.green, 'x', c.blue + number, c.violet, '=', int(number) * count, c.reset)
