#!/usr/bin/env python3

import colors as c
import random
import fluffy as quiz

print(c.magenta + "Welocme to my quiz Would You like to take the fluffy or capitals quiz")

quiz.q1()
quiz.q2()
quiz.q3()









