#!/usr/bin/env python3

import colors as c

sides = []

sides.append('''
 -------
|       |
|   o   |
|       |
 -------
''')

sides.append('''
 -------
| o     |
|       |
|     o | 
 -------
''')

sides.append('''
 -------
| o     |
|   o   |
|     o |
 -------
''')

sides.append('''
 -------
| o   o |
|       |
| o   o |
 -------
''')

sides.append('''
 -------
| o   o |
|   o   |
| o   o |
 -------
''')

sides.append('''
 -------
| o   o |
| o   o |
| o   o |
 -------
''')

import random

while True:
    side = random.choice(sides)
    print(c.clear + c.random_color() + side + c.reset)
    input()
