#!/usr/bin/env python3


import time
import colors as c

seconds = 0
minutes = 0

while True:    
    print(c.clear) 
    print(c.cyan + '[control-c to stop]: ' + c.reset)
    print(seconds)
    time.sleep(1)
    seconds += 1
    print(minutes)
    time.sleep(60)
    minutes += 1



















